### ISSUE TITLE
Make certain target details publicly accessible

### ISSUE THREAD

**Issue by proditis** [echoCTF/echoCTF.RED#14]
* [x] Make target/view publicly accessible (with limited details). 
* [x] Include appropriate meta tags for twitter "product" display
* [x] ~~Create dynamic logo generation for each target~~ (split into #33, #34, #35)
* [x] ~~Create dynamic badge image generation for each target~~ (split into #33, #34, #35)
* [x] Create our own custom tweet button and add on page (split into #31 and #32)

**Comment by proditis** [comment]
Add something like this
```
<a href="https://twitter.com/intent/tweet?url=http%3a%2f%2fwww.tomtunguz.com%2fimportance-and-mystery-demand-generation%2f&text=Why%20Demand%20Generation%20Can%20Be%20So%20Challenging%20For%20Startups%20via%20@ttunguz&related=ttunguz">Share this post</a>
```
