### ISSUE TITLE
Documentation update checklist

### ISSUE THREAD

**Issue by proditis** [echoCTF/echoCTF.RED#67]
This issue is a placeholder for completing the existing documentation into being usable by others.

It is in direct relation with issue #66 

* [x] Ensure we document `sysconfig/set vpngw` on vpn
* [x] Include update instructions on docker specific documentation
* [x] Create a network architecture with example IP's so that users can understand how to setup
* [x] Rename interface group from dmz => `targets`
* [x] Separate the different document cases into their own markdown
